apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{.SpecialResource.Name}}-server-cert
spec:
  secretName: {{.SpecialResource.Name}}-server-cert
  commonName: {{.SpecialResource.Name}}-server
  dnsNames:
  - {{.SpecialResource.Name}}-service
  issuerRef:
    name: {{.SpecialResource.Name}}-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{.SpecialResource.Name}}-client-cert
spec:
  secretName: {{.SpecialResource.Name}}-client-cert
  commonName: {{.SpecialResource.Name}}-client
  issuerRef:
    name: {{.SpecialResource.Name}}-ca-issuer
    kind: Issuer
    group: cert-manager.io
