apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - 0001_secret.yaml
  - 0002_issuer.yaml
  - 0003_certificates.yaml
  - 0004_server.yaml
  - 0005_client.yaml
  name: ping-pong
namespace: ping-pong
