apiVersion: v1
entries:
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-29T12:30:28.754703436Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 82ddba0ff11d8cb8a8515fc861d4bbafc0bc5683f96caece4b5c109f01c64e77
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  connaisseur:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-07-29T12:30:28.755539505Z"
    description: A Helm chart for the Connaisseur Admission Controller
    digest: 7406f46ad064b12c097bca3d7a0f31d67eac1d99ea9638b4ede3669761e8b493
    name: connaisseur
    type: application
    urls:
    - file:///charts/example/connaisseur-0.2.0.tgz
    version: 0.2.0
  multi-build:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-29T12:30:28.75576216Z"
    description: Showcase how to use multiple Builds with different DTKs
    digest: 8d110cf67f1070968fe90a507def12e1f1a4743f8726bbebf3ef3eda203e740a
    icon: https://avatars.githubusercontent.com/u/55542927
    name: multi-build
    type: application
    urls:
    - file:///charts/example/multi-build-0.0.1.tgz
    version: 0.0.1
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-29T12:30:28.756086957Z"
    description: Simple go app to showcase cert-manager intergration
    digest: 8476b7fae58df09a5b8ff00d5a7fbc378275cdca97a8e466a0896b9320f6c56b
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-29T12:30:28.75624029Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 8cfb6dc0f8d14a6df3386bfa04ea222067a9324ac0427c96d42f6dc8699dccba
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-07-29T12:30:28.75440481Z"
