apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-08-04T09:07:52.074937675Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: c36cd19e8691a68856d51df87de14fac527aec7ca04eaac5e6a57935daccba6d
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-04T09:07:52.074544546Z"
